warps:
  oak:
    world: world
    x: 28
    y: 40
    z: -11
    yaw: -180
    pitch: 0
  stone:
    world: world
    x: 28
    y: 40
    z: 7
    yaw: 0
    pitch: 0
  copper:
    world: world
    x: 61
    y: 40
    z: -14
    yaw: -180
    pitch: 0
  coal:
    world: world
    x: 54
    y: 40
    z: 7
    yaw: 0
    pitch: 0
  iron:
    world: world
    x: 88
    y: 40
    z: 12
    yaw: 0
    pitch: 0
  gold:
    world: world
    x: 96
    y: 40
    z: -4
    yaw: -90
    pitch: 0
  diamond:
    world: world
    x: 97
    y: 40
    z: -61
    yaw: -90
    pitch: 0
  emerald:
    world: world
    x: 77
    y: 40
    z: -43
    yaw: 90
    pitch: 0
  netherite:
    world: world_nether
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
  blackstone:
    world: world_nether
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
  quartz:
    world: world_nether
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
  admin:
    world: world
    x: 10000
    y: 37
    z: 10000
    yaw: -180
    pitch: 0

spawn:
  world: world
  x: 0
  y: 41
  z: 0
  yaw: -90
  pitch: 0
